### ISSUE TITLE
Make device status indicator customizable for any of the available capabilities

### ISSUE THREAD

**Issue by StefanIndustries** [StefanIndustries/HomeyAsusWRT#12]

**Comment by VenominousX** [comment]
Hi Stefan, thank you for your great app. 
Is it possible to lower the polling interval for the online device check to 30 seconds?
![image](https://user-images.githubusercontent.com/66132770/180594836-5a8ec67c-ace0-4656-ac9f-1e355a0f8693.png)
Cheers

**Comment by StefanIndustries** [comment]
Hi @VenominousX ,

I noticed with my Homey (2016 version, non pro) that when increasing the intervals my Homey could get unresponsive, but I will make it optional with a warning in the next release.

**Comment by StefanIndustries** [comment]
https://github.com/StefanIndustries/HomeyAsusWRT/pull/20

Will be available in the next test version and later in the 'stable' release.
