### ISSUE TITLE
Temperatures

### ISSUE THREAD

**Issue by NAmRoD21v** [StefanIndustries/HomeyAsusWRT#29]
Could you add the following insights to the app:
- Temperature CPU
- Temperature 2.4 GHz
- Temperature 5 GHz

Thanks in advance.

**Comment by StefanIndustries** [comment]
Hi, sorry for the delay, I'm currently moving houses that is taking alot of my time.

Do you know if there is a way to get this info from the asus app on your mobile phone? if the info is not in the app I'm afraid I cannot find a way to integrate these insights.

**Comment by NAmRoD21v** [comment]
I don't think so. As far as I could find this data is only available when using Asuswrt-Merlin. Since that isn't official I don't think it will be in the app. Also when checking the app I couldn't find it unfortunately.

**Comment by StefanIndustries** [comment]
cannot add this feature unfortunately, I don't own a asus router that supports merlin and therefor I cannot add this with something like a feature toggle.
