### ISSUE TITLE
Support url instead ip only

### ISSUE THREAD

**Issue by rcaceiro** [StefanIndustries/HomeyAsusWRT#30]
Hello,
 I think that the plugin should support an URL http://192.168.1.1:8080, instead an IP to be limited in my configurations, as well support https, with a check if the user wants to accept with self signed certificate or not.

Nice plugin, by the way.

**Comment by StefanIndustries** [comment]
Hi, I have merged your pull request for the npm package, I am still testing your changes on the pull request for the homey app. will get back to this next week.

**Comment by rcaceiro** [comment]
HI @StefanIndustries I tried to do my best, if you need something please let me know

**Comment by rcaceiro** [comment]
@StefanIndustries I recall something right now, I forgot to migrate the configs when the user updates the app.

If someone has the app configured already you saved the ip only when they update, this plugin now expects the full url.
I can fix this if you want.

**Comment by StefanIndustries** [comment]
well, that is exactly what I was going to test before merging this PR, because that is absolutely necessary since over 1000 people have the app installed already ;)

**Comment by rcaceiro** [comment]
OK

**Comment by rcaceiro** [comment]
OK I think that the fix is correctly done. 
Behare that the version of node-asuswrt doesn't match, with no version, you have to make a release first or install locally.

**Comment by StefanIndustries** [comment]
I will test it later today, before I merge, please add your name to the developer array in the app.json, wouldn't want to miss out on some credits do you? ;)

**Comment by StefanIndustries** [comment]
```javascript
  "contributors": {
    "developers": [
      {
        "name": "Your name"
      }
    ]
  },
```

**Comment by StefanIndustries** [comment]
There is a small problem with the migration, you are not setting the new routerUrl I think. When installing your version all my devices break and I cannot repair them.

**Comment by rcaceiro** [comment]
I will check, thank you

**Comment by rcaceiro** [comment]
OK yes I missed the saving the url on migration and the repair process was fixed also.
Can you retry.
Sorry because I have https I couldn't use your pluggin so I cannot tested it.

**Comment by StefanIndustries** [comment]
I have the app running now and everything seems to be fine. will merge it tonight if no further issues arise.
